apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.dbSecret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.dbSecret.DB_PASSWORD | quote }}

