apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: wrouesnel/postgres_exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://username:password@db-host:5432/dbname?sslmode=disable"
