version: 3.8

services:
  web:
   build: .
   container_name: o2n_container
   ports:
     - 5000:5000
   environment:
     - FLASK_APP = app.py
     - FLASK_RUN_HOST =0.0.0.0
     - FLASK__ENV = production
  volumes:
     - .:/app
  depend_on:
      - db

db:
   image: postgres:alphine
   container_name: o2n_db
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: o2n_db
   volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
