apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: student-api
  ports:
    - protocol: TCP
      port: {{ .Values.ports.service.port }}
      targetPort: {{ .Values.ports.service.targetPort }}
  type: {{ .Values.service.type }}

