apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-api
data:
  APP_ENV: production
  APP_DEBUG: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: student-api
type: Opaque
stringData:
  SECRET_KEY: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application
      containers:
        - name: student-api
          image: rudrakshladdha/o2n:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          volumeMounts:
            - name: migrations-volume
              mountPath: /app/migrations
      volumes:
        - name: migrations-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

