apiVersion: v1
kind: Namespace
metadata:
  name: dependent-services

---
# Deployment for HashiCorp Vault
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: dependent-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      nodeSelector:
        type: dependent_services
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_LOCAL_CONFIG
              value: |
                {
                  "backend": {
                    "file": {
                      "path": "/vault/data"
                    }
                  },
                  "listener": {
                    "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": true
                    }
                  },
                  "default_lease_ttl": "168h",
                  "max_lease_ttl": "720h"
                }
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
           claimName: vault-pvc

---
# External Secrets Operator (ESO)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: dependent-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
    spec:
      nodeSelector:
        type: dependent_services
      containers:
        - name: external-secrets
          image: rudrakshladdha/o2n:latest
          env:
            - name: VAULT_ADDR
              value: "http://vault.dependent-services.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "root"

