apiVersion: v1
kind: ConfigMap
metadata:
  name: postman-collection
  namespace: student-api
data:
  collection.json: |
    {
      "collection": {
        "info": {
          "_postman_id": "7a7db72b-2afc-450b-af9e-afe6b0b98724",
          "name": "Student CRUD API",
          "description": "This is a collection for the Student CRUD API",
          "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
          "updatedAt": "2024-11-28T17:04:56.000Z",
          "createdAt": "2024-11-28T17:04:55.000Z",
          "lastUpdatedBy": "40077421",
          "uid": "40077421-7a7db72b-2afc-450b-af9e-afe6b0b98724"
        },
        "item": [
          {
            "name": "Add Student",
            "id": "b89f9217-1041-46c1-ab18-3fc5eec05be9",
            "protocolProfileBehavior": {
              "disableBodyPruning": true
            },
            "request": {
              "method": "POST",
              "header": [
                {
                  "key": "Content-Type",
                  "value": "application/json"
                }
              ],
              "body": {
                "mode": "raw",
                "raw": "{\n  \"name\": \"John Doe\",\n  \"age\": 20,\n  \"grade\": \"A\"\n}"
              },
              "url": {
                "raw": "http://localhost:5000/api/v1/students",
                "protocol": "http",
                "host": [
                  "localhost"
                ],
                "port": "5000",
                "path": [
                  "api",
                  "v1",
                  "students"
                ]
              }
            },
            "response": [],
            "uid": "40077421-b89f9217-1041-46c1-ab18-3fc5eec05be9"
          },
          {
            "name": "Get All Students",
            "id": "0374c37a-3e3f-41fb-86c0-d747a35ab0e2",
            "protocolProfileBehavior": {
              "disableBodyPruning": true
            },
            "request": {
              "method": "GET",
              "header": [],
              "url": {
                "raw": "http://localhost:5000/api/v1/students",
                "protocol": "http",
                "host": [
                  "localhost"
                ],
                "port": "5000",
                "path": [
                  "api",
                  "v1",
                  "students"
                ]
              }
            },
            "response": [],
            "uid": "40077421-0374c37a-3e3f-41fb-86c0-d747a35ab0e2"
          },
          {
            "name": "Get Student by ID",
            "id": "05b6080c-cac5-49f9-8611-8b067300c362",
            "protocolProfileBehavior": {
              "disableBodyPruning": true
            },
            "request": {
              "method": "GET",
              "header": [],
              "url": {
                "raw": "http://localhost:5000/api/v1/students/:id",
                "protocol": "http",
                "host": [
                  "localhost"
                ],
                "port": "5000",
                "path": [
                  "api",
                  "v1",
                  "students",
                  ":id"
                ],
                "variable": [
                  {
                    "id": "f241e13a-9727-4999-9574-c8e3b5d0af39",
                    "key": "id",
                    "value": "1"
                  }
                ]
              }
            },
            "response": [],
            "uid": "40077421-05b6080c-cac5-49f9-8611-8b067300c362"
          }
        ]
      }
    }

