name: student-api
namespace: student-api

replicas: 1
image: rudrakshladdha/o2n:latest
containerPort: 80

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "example.local"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
