apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: dependent-services
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: 9090

