name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE: rudrakshladdha/o2n
  DOCKER_USERNAME: rudrakshladdha # Ensure secrets are configured for sensitive data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose (if needed)
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 4: Build Docker Image
      - name: Build Backend Docker Image
        run: |
          echo "Building Backend Docker Image..."
          docker build -t rudrakshladdha/o2n:latest . 
          echo "Backend Docker Image built and tagged successfully."

      # Step 5: Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      # Step 6: Push Docker Image
      - name: Push Backend Docker Image
        run: |
          echo "Pushing Backend Docker Image..."
          docker push ${{ env.IMAGE }}:latest
          echo "Backend Docker Image pushed successfully."
