name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  BACKEND_IMAGE: rudrakshladdha/o2n

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          set -e
          VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4 || echo "v2.20.2")
          sudo curl -L "https://github.com/docker/compose/releases/download/$VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Backend Docker Image
        run: |
          echo "Building Docker Image with caching..."
          docker build --cache-from=type=registry,ref=$BACKEND_IMAGE:cache \
                       --cache-to=type=registry,mode=max,ref=$BACKEND_IMAGE:cache \
                       -t $BACKEND_IMAGE .
          echo "Docker Image built successfully."

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Backend Docker Image
        run: |
          echo "Pushing Backend Docker Image..."
          docker push $BACKEND_IMAGE:latest
          echo "Docker Image pushed successfully."
