
name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  BACKEND_IMAGE: rudrakshladdha/o2n
  DOCKER_USERNAME: rudrakshladdha # Use GitHub Secrets for Docker username

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Build Backend Docker Image
        run: |
          echo "Building  Docker Image..."
          docker build -t ${{ env.BACKEND_IMAGE }} .
          docker tag ${{ env.BACKEND_IMAGE }}:latest ${{ env.BACKEND_IMAGE }}:latest
          echo " Backend Docker Image built and tagged successfully."

    

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Push Backend Docker Image
        run: |
          echo "Pushing D Backend Docker Image..."
          docker push ${{ env.BACKEND_IMAGE }}:latest
          echo " Backend Docker Image pushed successfully."

     
